# Generated by Django 5.0.4 on 2024-05-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
