# Generated by Django 5.0.4 on 2024-05-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='default_email@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
