# Generated by Django 5.0.4 on 2024-05-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
