# Generated by Django 5.0.4 on 2024-05-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_remove_project_title_remove_project_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
