# Generated by Django 5.0.4 on 2024-06-12 15:48

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_newclassname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newclassname',
            name='file',
            field=models.FileField(),
        ),
    ]
