# Generated by Django 5.0.4 on 2024-06-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_newclassname_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
