# Generated by Django 5.0.4 on 2024-06-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_alter_newclassname_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='newclassname',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
