# Generated by Django 5.0.4 on 2024-06-12 22:45

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_newclassname_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newclassname',
            name='file',
            field=models.FileField(blank=True, upload_to=pages.models.user_directory_path),
        ),
    ]
