# Generated by Django 5.0.4 on 2024-06-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_alter_newclassname_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='newclassname',
            name='file_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
